[package]
name = "bebop-macro"
version = "0.1.0"
edition = "2018"
license = "BSD-2-Clause"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = { version = "1.0.72", features = ["parsing"] }
